import "./globals.css";
import Footer from "./ui/Footer";
import Header from "./ui/Header";
import { roboto } from "./ui/fonts";

export const metadata = {
  title: "Web studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased text-mainTextColor`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
