import "./globals.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import { roboto } from "./ui/fonts";

export const metadata = {
  title: "Web studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="uk">
      <body className={`${roboto.className} antialiased text-mainTextColor`}>
      <h1 className="visually-hidden">Веб студія</h1>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
