import React from "react";
import PortfoliComponent from "../components/PortfoliComponent";

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function Portfolio() {
  return (
    <article className="my-[60px] flex-auto">
      <h2 className="visually-hidden">Портфоліо</h2>
      <PortfoliComponent />
    </article>
  );
}
